# Generated by Django 4.2.7 on 2023-11-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teacherprofile_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianprofile',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
