# Generated by Django 4.2.7 on 2023-11-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_guardianprofile_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentclass'),
        ),
    ]
