# Generated by Django 4.2.7 on 2023-11-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='invite_code',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
