# Generated by Django 4.2.7 on 2023-11-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_guardianprofile_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianprofile',
            old_name='student',
            new_name='students',
        ),
    ]
