# Generated by Django 4.2.7 on 2023-11-28 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_student_guardianprofile_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('std', 'Student'), ('tchr', 'Teacher'), ('grd', 'Guardian')], default='tchr', editable=False, max_length=10),
        ),
    ]
