# Generated by Django 4.2.7 on 2023-11-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='StudentGroup',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='class_id',
            new_name='group',
        ),
    ]
