# Generated by Django 4.2.7 on 2023-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_studentclass_studentgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
