# Generated by Django 4.2.7 on 2023-11-29 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_studentgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.studentgroup'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
