version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - .data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vschool
    ports:
      - "5432:5432"
    
  django:
    build: 
      context: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=asndfjkasdfklmasoefj09asefmasle;mf;lasmdlfasef
      - ALLOWED_HOSTS=localhost,127.0.0.1,testserver
    depends_on:
      - db

