# Generated by Django 4.2.7 on 2023-12-04 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_time',
            field=models.CharField(choices=[('1', '8:00 - 8:45'), ('2', '9:00 - 9:45'), ('3', '10:00 - 10:45'), ('4', '11:00 - 11:45'), ('5', '12:00 - 12:45'), ('6', '13:00 - 13:45'), ('7', '14:00 - 14:45')], max_length=50),
        ),
    ]
