# Generated by Django 4.2.7 on 2023-12-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_lesson_date_alter_lesson_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date_time',
            new_name='time_slot',
        ),
    ]
