# Generated by Django 4.2.7 on 2023-12-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_homework_options_alter_lesson_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.schedule'),
        ),
    ]
