# Generated by Django 4.2.7 on 2023-12-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_schedule_lesson_lesson_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='docs.schedule'),
        ),
    ]
