# Generated by Django 4.2.7 on 2023-12-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_id'),
        ('docs', '0006_alter_lesson_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='docs.lesson')),
                ('student', models.ManyToManyField(to='users.studentprofile')),
            ],
        ),
    ]
