# Generated by Django 4.2.7 on 2023-12-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='students',
        ),
    ]
